ALTER TABLE ospos_customers` ADD `anniversary` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `date`;

ALTER TABLE ospos_customers` ADD `anniversary` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `dob`;

